<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOdzbqWz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOdzbqWz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOdzbqWz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOdzbqWz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOdzbqWz\App_KernelDevDebugContainer([
    'container.build_hash' => 'OdzbqWz',
    'container.build_id' => '8ac98c36',
    'container.build_time' => 1673787065,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOdzbqWz');
